export const WEATHER_API_REQUEST = "WEATHER_API_REQUEST";
export const WEATHER_API_SUCCESS = "WEATHER_API_SUCCESS";
export const WEATHER_API_FAILURE = "WEATHE_API_FAILURE";
export const WEATHE_API_DATA_RESET = "WEATHER_API_DATA_RESET";